services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=dev
      - DEBUG=true
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    tty: true
  db:
    image: postgres:17.4
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres