services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    # - ./seed:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project_db"]
      interval: 2s
      timeout: 3s
      retries: 20

  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/project_db
      REDIS_URL: redis://redis:6379/0
      APP_ENV: dev
      DEBUG: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    tty: true

  migrate:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/project_db
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head